### PR TITLE
Fix copy paste

### PR DESCRIPTION
**Pull request by mdaxtman**
fix `copy`/`paste` bug, is necessary to have them embedded into app menu for them to work. Added `cut` and `select-all` as well. "Delete Element" is now `Backspace` unable to test on Linux and Windows at the moment, but works on Mac and doesn't interfere with `backspace` during text edits.

### CODE REVIEW

**Comment by rgerstenberger** [comment]
Looks like you only added cut/copy/paste to darwin. Are the other menus up to snuff?

**Comment by mdaxtman** [comment]
I cannot test for Linux/Windows right now, but as I looked through the commit history there were not any old instances of copy/paste for those platforms. Unless someone deleted the boilerplate for them long ago and I never caught it, I would guess it was never there. But you're right, we shouldn't be assuming it will work.

**Comment by rgerstenberger** [comment]
Ok, this looks good, merge away. Add a ticket for getting menu parity on the other platforms.

**Comment by mdaxtman** [comment]
will do.

**Pull request merged**
