### PR TITLE
Chore: Initial iframe drag placeholder image

### PR DESCRIPTION
**Pull request by rgerstenberger**
This makes the preview item for an iframe drag a placeholder image so that dragging outside of the canvas does not reload the iframe and cause network requests. The next step would be to have our default embedded graph load from disk instead of make a network request.

/cc @kenwheeler @sethvincent 
may-31-2016 16-06-23

### CODE REVIEW

**Comment by sethvincent** [comment]
It would be nice if the placeholder image were a local file to help with offline use.

**Comment by rgerstenberger** [comment]
@sethvincent good call and it is :)

**Comment by sethvincent** [comment]
oh :+1:

**Comment by kenwheeler** [comment]
LGTM

**Pull request merged**
