### PR TITLE
Fix lowercase fonts

### PR DESCRIPTION
**Pull request by mdaxtman**
@rgerstenberger paths in linux are case sensitive, all font files had to be renamed to be all lower case file names.

### CODE REVIEW

**Comment by coopy** [comment]
The change itself looks good. However, I am having trouble understanding why this change fixes anything – since case is important in Linux, Linux should also be able to understand how to deal with CapitalCamelCase font names... I'd just like to understand what the root cause is.

**Comment by ryan-roemer** [comment]
Also side comment -- for all JS / CSS files, we should ideally _always_ use lower case (dash or snake case). Uppercasing in file names is an anti-pattern, because it only has "I like this convention" advantages, and many practical "breaks things on different platforms" disadvantages -- which should inform us to never do uppercasing...

**Comment by coopy** [comment]
I'm interested in hearing a diagnosis of what actually break, but I'm 👍 for merging this

**Comment by rgerstenberger** [comment]
Can we standardize on kabab-case? Some of the files are underscored.

**Comment by mdaxtman** [comment]
@coopy here is the error itself as webpack attempts to build the modules. It appears to possibly be webpack loaders. Changing these filenames to all lowercase resolves this.

@ryan-roemer @rgerstenberger unfortunately, we kept the original case and naming conventions that were used from the original font files. I'll update to kebab case.

screenshot from 2016-08-01 14 24 21

**Pull request merged**
