### PR TITLE
Feature keyboard events

### PR DESCRIPTION
**Pull request by mdaxtman**
@rgerstenberger 

Undo, redo, and escape to finalize have been implemented on text editor. The undo/redo functionality is only partially working, due to some faulty issues with `execCommand("redo")` not repeating all actions for some reason. In the interest of time it was decided not to pursue creating a history stack for the text editor and implementing undo/redo functionality from scratch as it was slowing productivity. We can circle back to this as you like, and I can file an issue as well. Otherwise, I or someone else can tackle it ASAP.

remove resize nodes and arrange component when editing.

Add menu items for windows and Mac with keyboard events and enabled/disabled context based upon element selection.

screen shot 2016-07-28 at 3 17 24 pm
screen shot 2016-07-28 at 3 17 35 pm

### CODE REVIEW

**Comment by rgerstenberger** [comment]
I'm confused, why is undo/redo broken? It's working fine in master

**Comment by rgerstenberger** [comment]
Can you remove the rest of the menu that doesn't apply to our app? Everything below delete element.

**Comment by mdaxtman** [comment]
Undo/redo is partially working on text edits. Globally it still works fine.

**Comment by rgerstenberger** [comment]
LGTM! Fix CI tho.

**Pull request merged**
