### PR TITLE
Style add/delete slide icons

### PR DESCRIPTION
**Pull request by paulathevalley**
- Add add slide & delete slide icons 
- Move the menu to the bottom, and use flex to keep it fixed as slide outline grows

The blue highlighting for the selected slide looks weird, but it looked weird on `master`, too. :cry: 

/cc @rgerstenberger 

screen shot 2016-07-12 at 6 33 54 pm

### CODE REVIEW

**Comment by rgerstenberger** [comment]
@kenwheeler can you take a look at the issue? I think some styles were updated that affect the list and I didn't do my due diligence :/

**Comment by kenwheeler** [comment]
Trying to find the offending styles. It looks like if you take this branch, and open index.js in slide-menu, changing line 286 to 140 instead of slideHeight fixes it, but I'm going to look further because I haven't identified the exact cause, might be a better fix somewhere

**Comment by kenwheeler** [comment]
Ok, it looks like the root cause is here https://github.com/FormidableLabs/spectacle-editor/commit/d17d4302daffa0678e9284f288c17ca338cfa527, the conversion border-box universally. A simpler and more reliable fix for this branch would be to add `box-sizing: content-box` to `.slideOuter` in `slide-menu/index.css`. Confirmed working on this branch

**Comment by rgerstenberger** [comment]
@kenwheeler can you just push the fix on this branch please? 💃

**Comment by kenwheeler** [comment]
💥

**Comment by paulathevalley** [comment]
Daaaang! Thanks for the inspection and quick fix. I should have expected consequences from normalizing so late. I'll keep a lookout for more, and `border-box` should be much nicer. :pray:  

Is this good to :dancer: merge :dancer:?

**Comment by rgerstenberger** [comment]
Yes, approved! Merge away 👯

**Pull request merged**
